apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"11.2.2-security-01","helm.sh/chart":"grafana-8.5.8"},"name":"grafana","namespace":"istio-system"},"spec":{"ports":[{"name":"service","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/name":"grafana"},"type":"ClusterIP"}}

      '
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.2-security-01
    helm.sh/chart: grafana-8.5.8
  name: grafana
  namespace: istio-system
spec:
  clusterIP: 10.102.211.204
  ports:
  - name: service
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
