apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jaeger"},"name":"jaeger-collector","namespace":"istio-system"},"spec":{"ports":[{"name":"jaeger-collector-http","port":14268,"protocol":"TCP","targetPort":14268},{"name":"jaeger-collector-grpc","port":14250,"protocol":"TCP","targetPort":14250},{"name":"http-zipkin","port":9411,"targetPort":9411},{"name":"grpc-otel","port":4317},{"name":"http-otel","port":4318}],"selector":{"app":"jaeger"},"type":"ClusterIP"}}

      '
  labels:
    app: jaeger
  name: jaeger-collector
  namespace: istio-system
spec:
  clusterIP: 10.111.121.135
  ports:
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: jaeger-collector-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: http-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: grpc-otel
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otel
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: jaeger
  sessionAffinity: None
  type: ClusterIP
