apiVersion: v1
items:
- apiVersion: networking.istio.io/v1
  kind: VirtualService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.istio.io/v1","kind":"VirtualService","metadata":{"annotations":{},"name":"bookinfo","namespace":"default"},"spec":{"gateways":["bookinfo-gateway"],"hosts":["productpage.bookinfo.com"],"http":[{"match":[{"uri":{"exact":"/productpage"}},{"uri":{"prefix":"/static"}},{"uri":{"exact":"/login"}},{"uri":{"exact":"/logout"}},{"uri":{"prefix":"/api/v1/products"}}],"route":[{"destination":{"host":"productpage","port":{"number":9080}}}]}]}}
    creationTimestamp: "2024-12-09T01:34:32Z"
    generation: 4
    name: bookinfo
    namespace: default
    resourceVersion: "329243"
    uid: ea34e520-a81f-4989-b009-41932acf703a
  spec:
    gateways:
    - bookinfo-gateway
    hosts:
    - productpage.bookinfo.com
    http:
    - match:
      - uri:
          exact: /productpage
      - uri:
          prefix: /static
      - uri:
          exact: /login
      - uri:
          exact: /logout
      - uri:
          prefix: /api/v1/products
      route:
      - destination:
          host: productpage
          port:
            number: 9080
- apiVersion: networking.istio.io/v1
  kind: VirtualService
  metadata:
    creationTimestamp: "2025-01-07T07:56:58Z"
    generation: 1
    labels:
      kiali_wizard: traffic_shifting
    name: reviews
    namespace: default
    resourceVersion: "330767"
    uid: c0d053b0-7053-4f0f-ba92-fae7e63724d1
  spec:
    hosts:
    - reviews.default.svc.cluster.local
    http:
    - route:
      - destination:
          host: reviews.default.svc.cluster.local
          subset: v1
        weight: 33
      - destination:
          host: reviews.default.svc.cluster.local
          subset: v2
        weight: 33
      - destination:
          host: reviews.default.svc.cluster.local
          subset: v3
        weight: 34
- apiVersion: networking.istio.io/v1
  kind: DestinationRule
  metadata:
    creationTimestamp: "2025-01-07T07:56:58Z"
    generation: 1
    labels:
      kiali_wizard: traffic_shifting
    name: reviews
    namespace: default
    resourceVersion: "330766"
    uid: edec9b1f-f367-4fe6-b120-0bf003c6c053
  spec:
    host: reviews.default.svc.cluster.local
    subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
    - labels:
        version: v3
      name: v3
- apiVersion: networking.istio.io/v1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.istio.io/v1","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"default"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":8080,"protocol":"HTTP"}}]}}
    creationTimestamp: "2024-12-09T01:34:32Z"
    generation: 3
    name: bookinfo-gateway
    namespace: default
    resourceVersion: "329227"
    uid: c1362168-cdef-4af4-bbb2-9761c545d38a
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 8080
        protocol: HTTP
kind: List
metadata:
  resourceVersion: ""
