apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"zipkin"},"name":"zipkin","namespace":"istio-system"},"spec":{"ports":[{"name":"http-query","port":9411,"targetPort":9411}],"selector":{"app":"jaeger"}}}

      '
  labels:
    name: zipkin
  name: zipkin
  namespace: istio-system
spec:
  clusterIP: 10.110.81.206
  ports:
  - name: http-query
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
  sessionAffinity: None
  type: ClusterIP
