apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"checkoutservice"},"name":"checkoutservice","namespace":"online-boutique"},"spec":{"ports":[{"name":"grpc","port":5050,"targetPort":5050}],"selector":{"app":"checkoutservice"},"type":"ClusterIP"}}

      '
  labels:
    app: checkoutservice
  name: checkoutservice
  namespace: online-boutique
spec:
  clusterIP: 10.107.228.12
  ports:
  - name: grpc
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: checkoutservice
  sessionAffinity: None
  type: ClusterIP
