apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"currencyservice"},"name":"currencyservice","namespace":"online-boutique"},"spec":{"ports":[{"name":"grpc","port":7000,"targetPort":7000}],"selector":{"app":"currencyservice"},"type":"ClusterIP"}}

      '
  labels:
    app: currencyservice
  name: currencyservice
  namespace: online-boutique
spec:
  clusterIP: 10.104.240.242
  ports:
  - name: grpc
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: currencyservice
  sessionAffinity: None
  type: ClusterIP
