apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
spec:
  clusterIP: 10.96.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  selector: null
  sessionAffinity: None
  type: ClusterIP
