apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.istio.io/v1alpha3","kind":"DestinationRule","metadata":{"annotations":{},"name":"productpage","namespace":"default"},"spec":{"host":"productpage","subsets":[{"labels":{"version":"v1"},"name":"v1"},{"labels":{"version":"v2"},"name":"v2"}]}}

      '
  creationTimestamp: '2025-04-03T07:25:50Z'
  generation: 1
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:host: {}
        f:subsets: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: '2025-04-03T07:25:50Z'
  name: productpage
  namespace: default
  resourceVersion: '1482342'
  uid: 8f68a648-6bc7-4436-8ea2-132859b7e95c
spec:
  host: productpage
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
