apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"frontend","namespace":"online-boutique"},"spec":{"hosts":["frontend.default.svc.cluster.local"],"http":[{"route":[{"destination":{"host":"frontend","port":{"number":80}}}]}]}}

      '
  creationTimestamp: '2025-03-20T09:19:48Z'
  generation: 6
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: '2025-03-20T09:19:48Z'
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:hosts: {}
        f:http: {}
    manager: kiali
    operation: Update
    time: '2025-04-03T08:55:08Z'
  name: frontend
  namespace: online-boutique
  resourceVersion: '1496582'
  uid: e0d965fe-cd4b-42b6-8916-39045e5b4c33
spec:
  hosts:
  - frontend.online-boutique.svc.cluster.local
  http:
  - route:
    - destination:
        host: frontend
        port:
          number: 80
