apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: '2025-01-07T07:56:58Z'
  generation: 1
  labels:
    kiali_wizard: traffic_shifting
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kiali_wizard: {}
      f:spec:
        .: {}
        f:host: {}
        f:subsets: {}
    manager: kiali
    operation: Update
    time: '2025-01-07T07:56:58Z'
  name: reviews
  namespace: default
  resourceVersion: '330766'
  uid: edec9b1f-f367-4fe6-b120-0bf003c6c053
spec:
  host: reviews.default.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
  - labels:
      version: v3
    name: v3
