apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: '2025-01-07T07:56:58Z'
  generation: 45
  labels:
    kiali_wizard: traffic_shifting
  managedFields:
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kiali_wizard: {}
      f:spec:
        .: {}
        f:hosts: {}
        f:http: {}
    manager: kiali
    operation: Update
    time: '2025-04-03T15:20:27Z'
  name: reviews
  namespace: default
  resourceVersion: '1555856'
  uid: c0d053b0-7053-4f0f-ba92-fae7e63724d1
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        source:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
